# Generated by Django 5.1.7 on 2025-04-09 22:48

import ckeditor.fields
import django.core.validators
import django.utils.timezone
import icma.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_header', models.CharField(help_text='Iltimos, maqola sarlavhasini kiriting.', max_length=50, verbose_name='maqola sarlavhasi')),
                ('a_paragraph', ckeditor.fields.RichTextField(help_text='Iltimos, maqola matnini kiriting.', verbose_name='maqola matni')),
                ('a_date', models.DateField(default=django.utils.timezone.now, help_text='Iltimos, maqola sanasini kiriting.', verbose_name='maqola sanasi')),
                ('a_view_counter', models.IntegerField(default=0, verbose_name="maqola ko'rishlar soni")),
                ('a_article_img', models.ImageField(help_text='Iltimos, rasm yuklang (.jpg, .jpeg, .png formatlarida)!', upload_to='article/', validators=[icma.validators.valid_url_extension], verbose_name='maqola rasmi')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateField(auto_now=True, verbose_name="o'zgartirilgan vaqti")),
            ],
            options={
                'verbose_name': 'Maqola',
                'verbose_name_plural': 'Maqolalar',
            },
        ),
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_header', models.CharField(help_text='Iltimos, markaz sarlavhasini kiriting.', max_length=50, verbose_name='markaz sarlavhasi')),
                ('c_paragraph', ckeditor.fields.RichTextField(help_text='Iltimos, markaz matnini kiriting.', verbose_name='markaz matni')),
                ('c_center_img_1', models.ImageField(help_text='Iltimos, rasm yuklang (.jpg, .jpeg, .png formatlarida)!', upload_to='center/', validators=[icma.validators.valid_url_extension], verbose_name='markaz rasmi')),
                ('c_center_img_2', models.ImageField(help_text='Iltimos, rasm yuklang (.jpg, .jpeg, .png formatlarida)!', upload_to='center/', validators=[icma.validators.valid_url_extension], verbose_name='markaz rasmi')),
                ('c_center_img_3', models.ImageField(help_text='Iltimos, rasm yuklang (.jpg, .jpeg, .png formatlarida)!', upload_to='center/', validators=[icma.validators.valid_url_extension], verbose_name='markaz rasmi')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateField(auto_now=True, verbose_name="o'zgartirilgan vaqti")),
            ],
            options={
                'verbose_name': 'Markaz',
                'verbose_name_plural': 'Markazlar',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_fname', models.CharField(help_text='Iltimos, to‘liq ismingizni kiriting.', max_length=50, verbose_name='toliq ism')),
                ('c_email', models.EmailField(help_text='Iltimos, email manzilingizni kiriting.', max_length=254, validators=[icma.validators.validate_email], verbose_name='pochta manzili')),
                ('c_phone_number', models.CharField(error_messages={'invalid': 'Iltimos, to‘g‘ri telefon raqamini kiriting.'}, help_text='Iltimos, telefon raqamingizni kiriting. Masalan: +998123456789', max_length=13, validators=[icma.validators.PhoneValidator()], verbose_name='Telefon raqami')),
                ('c_theme', models.CharField(blank=True, help_text='Iltimos, xabaringiz mavzusini kiriting.', max_length=50, null=True, verbose_name='Mavzu')),
                ('c_message', models.TextField(blank=True, help_text='Iltimos, xabaringizni shu yerga yozing.', null=True, verbose_name='Xabar matni')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='O‘zgartirilgan vaqti')),
            ],
            options={
                'verbose_name': 'Aloqa',
                'verbose_name_plural': 'Aloqalar',
            },
        ),
        migrations.CreateModel(
            name='Corruption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_corrupt_file', models.FileField(help_text='Iltimos, faylingizni yuklang!', upload_to='korrupsiya/', verbose_name='korrupsiya fayli')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateField(auto_now=True, verbose_name="o'zgartirilgan vaqti")),
            ],
            options={
                'verbose_name': 'Korrupsiya',
                'verbose_name_plural': 'Korrupsiyalar',
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Iltimos, rahbarning to‘liq ism-sharifini kiriting!', max_length=50, validators=[icma.validators.validate_f_name], verbose_name='toliq_ism')),
                ('p_number', models.CharField(error_messages={'invalid': 'Iltimos, to‘g‘ri telefon raqamini kiriting!'}, help_text='Iltimos, direktorning telefon raqamini kiriting. Masalan: +998123456789', max_length=13, validators=[icma.validators.PhoneValidator()], verbose_name='telefon_raqam')),
                ('email', models.EmailField(help_text='Iltimos, Email manzilingizni kiriting.', max_length=254, validators=[icma.validators.validate_email], verbose_name='pochta')),
                ('biography', models.TextField(help_text='Iltimos, direktorning biografiyasini kiriting.', verbose_name='biografiya')),
                ('director_img', models.ImageField(help_text='Iltimos, direktorning fotosuratini yuklang (.jpg, .jpeg, .png formatlarida)!', upload_to='director/', validators=[icma.validators.valid_url_extension], verbose_name='rahbar_rasmi')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateField(auto_now=True, verbose_name="o'zgartirilgan vaqti")),
            ],
            options={
                'verbose_name': 'Direktor',
                'verbose_name_plural': 'Direktorlar',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_full_name', models.CharField(help_text='Iltimos, xodimning to‘liq ismini kiriting.', max_length=50, validators=[icma.validators.validate_f_name], verbose_name='xodimning toliq ism')),
                ('emp_speciality', models.CharField(help_text='Iltimos, xodimning mutaxassisligini kiriting.', max_length=50, verbose_name='xodimning mutaxassisligi')),
                ('employees_img', models.ImageField(help_text='Iltimos, xodimning fotosuratini yuklang (.jpg, .jpeg, .png formatlarida)!', upload_to='employee/', validators=[icma.validators.valid_url_extension], verbose_name='xodimning surati')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateField(auto_now=True, verbose_name="o'zgartirilgan vaqti")),
            ],
            options={
                'verbose_name': 'Xodim',
                'verbose_name_plural': 'Xodimlar',
            },
        ),
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inf_img', models.ImageField(help_text='Iltimos, rasmingizni yuklang!', upload_to='infrostructure/', verbose_name='infroni surati')),
                ('inf_header', models.CharField(default=' ', help_text='Iltimos, infrotuzilma sarlavhasini kiriting.', max_length=100, verbose_name='infrotuzilma sarlavhasi')),
                ('inf_paragraph', models.TextField(default=' ', help_text='Iltimos, infrotuzilma matnini kiriting.', verbose_name='infrotuzilma matni')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateField(auto_now=True, verbose_name="o'zgartirilgan vaqti")),
            ],
            options={
                'verbose_name': 'Infrostruktura',
                'verbose_name_plural': 'Infrostrukturalar',
            },
        ),
        migrations.CreateModel(
            name='Monitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_header', models.CharField(help_text='Iltimos, monitoring sarlavhasini kiriting.', max_length=50, verbose_name='monitoring sarlavhasi')),
                ('m_paragraph', models.TextField(help_text='Iltimos, monitoring matnini kiriting.', verbose_name='monitoring matni')),
                ('m_date', models.DateField(default=django.utils.timezone.now, help_text='Iltimos, monitoring sanasini kiriting.', verbose_name='monitoring sanasi')),
                ('m_view_counter', models.IntegerField(default=0, verbose_name="monitoring ko'rishlar soni")),
                ('status', models.SmallIntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=0, help_text='Iltimos, kartaning holatini kiriting.', verbose_name='holati')),
                ('m_img', models.ImageField(help_text='Iltimos, monitoring uchun rasm yuklang (.jpg, .jpeg, .png formatlarida)!', upload_to='monitoring/', validators=[icma.validators.valid_url_extension], verbose_name='monitoring rasmi')),
                ('m_file', models.FileField(help_text='Iltimos, faylingizni yuklang!', upload_to='monitoring/', verbose_name='monitoring fayli')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateField(auto_now=True, verbose_name="o'zgartirilgan vaqti")),
            ],
            options={
                'verbose_name': 'Monitoring',
                'verbose_name_plural': 'Monitoringlar',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_header', models.CharField(help_text='Iltimos, yangilik sarlavhasini kiriting.', max_length=50, verbose_name='yangilik sarlavhasi')),
                ('n_paragraph', ckeditor.fields.RichTextField(help_text='Iltimos, yangilik matnini kiriting.', verbose_name='yangilik matni')),
                ('n_date', models.DateField(default=django.utils.timezone.now, help_text='Iltimos, yangilik sanasini kiriting.', verbose_name='yangilik sanasi')),
                ('n_view_counter', models.PositiveIntegerField(default=0, verbose_name="yangilik ko'rishlar soni")),
                ('n_news_img', models.ImageField(help_text='Iltimos, fotosurat yuklang (.jpg, .jpeg, .png formatlarida)!', upload_to='news/', validators=[icma.validators.valid_url_extension], verbose_name='yangilik rasmi')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateField(auto_now=True, verbose_name="o'zgartirilgan vaqti")),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': 'Yangiliklar',
            },
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_fname', models.CharField(help_text='Iltimos, pasport egasining ismini kiriting.', max_length=50, verbose_name='Pasport egasining ismi')),
                ('p_code', models.CharField(help_text='Iltimos, pasport kodini kiriting.', max_length=7, validators=[django.core.validators.RegexValidator(message='Pasport raqami aniq 7 ta harf yoki raqamdan iborat bo‘lishi kerak.', regex='^[A-Za-z0-9]{7}$')], verbose_name='Pasport kodi')),
                ('p_email', models.EmailField(help_text='Iltimos, email manzilingizni kiriting.', max_length=254, validators=[icma.validators.validate_email], verbose_name='Email manzili')),
                ('given_date', models.DateField(blank=True, default=django.utils.timezone.now, help_text='Iltimos, pasport berilgan sanani kiriting.', null=True, validators=[icma.validators.validate_date], verbose_name='Berilgan sana')),
                ('p_img_upl', models.FileField(help_text='Iltimos, pasport rasmini yuklang.', upload_to='passport/', verbose_name='Pasport rasmi')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='O‘zgartirilgan vaqti')),
            ],
            options={
                'verbose_name': 'Passport',
                'verbose_name_plural': 'Passportlar',
            },
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_employeements', models.PositiveIntegerField(help_text='Iltimos, xodimlar sonini kiriting.', verbose_name='statistika xodimlar')),
                ('s_partners', models.PositiveIntegerField(help_text='Iltimos, Xamkorlar sonini kiriting.', verbose_name='statistika xamkorlar')),
                ('s_treateds', models.PositiveIntegerField(help_text='Iltimos, Davolanganlar sonini kiriting.', verbose_name='statistika davolanganlar')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='O‘zgartirilgan vaqti')),
            ],
            options={
                'verbose_name': 'Statistika',
                'verbose_name_plural': 'Statistikalar',
            },
        ),
    ]
