# Generated by Django 5.1.7 on 2025-04-10 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corruption',
            name='c_corrupt_file',
            field=models.FileField(blank=True, help_text='Iltimos, faylingizni yuklang!', null=True, upload_to='korrupsiya/', verbose_name='korrupsiya fayli'),
        ),
    ]
