# Generated by Django 5.1.7 on 2025-04-13 05:50

import ckeditor.fields
import icma.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icma', '0002_alter_corruption_c_corrupt_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='a_header_en',
            field=models.CharField(help_text='Iltimos, maqola sarlavhasini kiriting.', max_length=50, null=True, verbose_name='maqola sarlavhasi'),
        ),
        migrations.AddField(
            model_name='article',
            name='a_header_ru',
            field=models.CharField(help_text='Iltimos, maqola sarlavhasini kiriting.', max_length=50, null=True, verbose_name='maqola sarlavhasi'),
        ),
        migrations.AddField(
            model_name='article',
            name='a_header_uz',
            field=models.CharField(help_text='Iltimos, maqola sarlavhasini kiriting.', max_length=50, null=True, verbose_name='maqola sarlavhasi'),
        ),
        migrations.AddField(
            model_name='article',
            name='a_paragraph_en',
            field=ckeditor.fields.RichTextField(help_text='Iltimos, maqola matnini kiriting.', null=True, verbose_name='maqola matni'),
        ),
        migrations.AddField(
            model_name='article',
            name='a_paragraph_ru',
            field=ckeditor.fields.RichTextField(help_text='Iltimos, maqola matnini kiriting.', null=True, verbose_name='maqola matni'),
        ),
        migrations.AddField(
            model_name='article',
            name='a_paragraph_uz',
            field=ckeditor.fields.RichTextField(help_text='Iltimos, maqola matnini kiriting.', null=True, verbose_name='maqola matni'),
        ),
        migrations.AddField(
            model_name='center',
            name='c_header_en',
            field=models.CharField(help_text='Iltimos, markaz sarlavhasini kiriting.', max_length=50, null=True, verbose_name='markaz sarlavhasi'),
        ),
        migrations.AddField(
            model_name='center',
            name='c_header_ru',
            field=models.CharField(help_text='Iltimos, markaz sarlavhasini kiriting.', max_length=50, null=True, verbose_name='markaz sarlavhasi'),
        ),
        migrations.AddField(
            model_name='center',
            name='c_header_uz',
            field=models.CharField(help_text='Iltimos, markaz sarlavhasini kiriting.', max_length=50, null=True, verbose_name='markaz sarlavhasi'),
        ),
        migrations.AddField(
            model_name='center',
            name='c_paragraph_en',
            field=ckeditor.fields.RichTextField(help_text='Iltimos, markaz matnini kiriting.', null=True, verbose_name='markaz matni'),
        ),
        migrations.AddField(
            model_name='center',
            name='c_paragraph_ru',
            field=ckeditor.fields.RichTextField(help_text='Iltimos, markaz matnini kiriting.', null=True, verbose_name='markaz matni'),
        ),
        migrations.AddField(
            model_name='center',
            name='c_paragraph_uz',
            field=ckeditor.fields.RichTextField(help_text='Iltimos, markaz matnini kiriting.', null=True, verbose_name='markaz matni'),
        ),
        migrations.AddField(
            model_name='director',
            name='biography_en',
            field=models.TextField(help_text='Iltimos, direktorning biografiyasini kiriting.', null=True, verbose_name='biografiya'),
        ),
        migrations.AddField(
            model_name='director',
            name='biography_ru',
            field=models.TextField(help_text='Iltimos, direktorning biografiyasini kiriting.', null=True, verbose_name='biografiya'),
        ),
        migrations.AddField(
            model_name='director',
            name='biography_uz',
            field=models.TextField(help_text='Iltimos, direktorning biografiyasini kiriting.', null=True, verbose_name='biografiya'),
        ),
        migrations.AddField(
            model_name='director',
            name='full_name_en',
            field=models.CharField(help_text='Iltimos, rahbarning to‘liq ism-sharifini kiriting!', max_length=50, null=True, validators=[icma.validators.validate_f_name], verbose_name='toliq_ism'),
        ),
        migrations.AddField(
            model_name='director',
            name='full_name_ru',
            field=models.CharField(help_text='Iltimos, rahbarning to‘liq ism-sharifini kiriting!', max_length=50, null=True, validators=[icma.validators.validate_f_name], verbose_name='toliq_ism'),
        ),
        migrations.AddField(
            model_name='director',
            name='full_name_uz',
            field=models.CharField(help_text='Iltimos, rahbarning to‘liq ism-sharifini kiriting!', max_length=50, null=True, validators=[icma.validators.validate_f_name], verbose_name='toliq_ism'),
        ),
        migrations.AddField(
            model_name='director',
            name='responsibility',
            field=models.TextField(blank=True, help_text='Iltimos, direktorning majburiyatlarini kiriting.', null=True, verbose_name='majburiyati'),
        ),
        migrations.AddField(
            model_name='director',
            name='responsibility_en',
            field=models.TextField(blank=True, help_text='Iltimos, direktorning majburiyatlarini kiriting.', null=True, verbose_name='majburiyati'),
        ),
        migrations.AddField(
            model_name='director',
            name='responsibility_ru',
            field=models.TextField(blank=True, help_text='Iltimos, direktorning majburiyatlarini kiriting.', null=True, verbose_name='majburiyati'),
        ),
        migrations.AddField(
            model_name='director',
            name='responsibility_uz',
            field=models.TextField(blank=True, help_text='Iltimos, direktorning majburiyatlarini kiriting.', null=True, verbose_name='majburiyati'),
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_full_name_en',
            field=models.CharField(help_text='Iltimos, xodimning to‘liq ismini kiriting.', max_length=50, null=True, validators=[icma.validators.validate_f_name], verbose_name='xodimning toliq ism'),
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_full_name_ru',
            field=models.CharField(help_text='Iltimos, xodimning to‘liq ismini kiriting.', max_length=50, null=True, validators=[icma.validators.validate_f_name], verbose_name='xodimning toliq ism'),
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_full_name_uz',
            field=models.CharField(help_text='Iltimos, xodimning to‘liq ismini kiriting.', max_length=50, null=True, validators=[icma.validators.validate_f_name], verbose_name='xodimning toliq ism'),
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_speciality_en',
            field=models.CharField(help_text='Iltimos, xodimning mutaxassisligini kiriting.', max_length=50, null=True, verbose_name='xodimning mutaxassisligi'),
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_speciality_ru',
            field=models.CharField(help_text='Iltimos, xodimning mutaxassisligini kiriting.', max_length=50, null=True, verbose_name='xodimning mutaxassisligi'),
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_speciality_uz',
            field=models.CharField(help_text='Iltimos, xodimning mutaxassisligini kiriting.', max_length=50, null=True, verbose_name='xodimning mutaxassisligi'),
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='inf_header_en',
            field=models.CharField(default=' ', help_text='Iltimos, infrotuzilma sarlavhasini kiriting.', max_length=100, null=True, verbose_name='infrotuzilma sarlavhasi'),
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='inf_header_ru',
            field=models.CharField(default=' ', help_text='Iltimos, infrotuzilma sarlavhasini kiriting.', max_length=100, null=True, verbose_name='infrotuzilma sarlavhasi'),
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='inf_header_uz',
            field=models.CharField(default=' ', help_text='Iltimos, infrotuzilma sarlavhasini kiriting.', max_length=100, null=True, verbose_name='infrotuzilma sarlavhasi'),
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='inf_paragraph_en',
            field=models.TextField(default=' ', help_text='Iltimos, infrotuzilma matnini kiriting.', null=True, verbose_name='infrotuzilma matni'),
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='inf_paragraph_ru',
            field=models.TextField(default=' ', help_text='Iltimos, infrotuzilma matnini kiriting.', null=True, verbose_name='infrotuzilma matni'),
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='inf_paragraph_uz',
            field=models.TextField(default=' ', help_text='Iltimos, infrotuzilma matnini kiriting.', null=True, verbose_name='infrotuzilma matni'),
        ),
        migrations.AddField(
            model_name='monitoring',
            name='m_header_en',
            field=models.CharField(help_text='Iltimos, monitoring sarlavhasini kiriting.', max_length=50, null=True, verbose_name='monitoring sarlavhasi'),
        ),
        migrations.AddField(
            model_name='monitoring',
            name='m_header_ru',
            field=models.CharField(help_text='Iltimos, monitoring sarlavhasini kiriting.', max_length=50, null=True, verbose_name='monitoring sarlavhasi'),
        ),
        migrations.AddField(
            model_name='monitoring',
            name='m_header_uz',
            field=models.CharField(help_text='Iltimos, monitoring sarlavhasini kiriting.', max_length=50, null=True, verbose_name='monitoring sarlavhasi'),
        ),
        migrations.AddField(
            model_name='monitoring',
            name='m_paragraph_en',
            field=models.TextField(help_text='Iltimos, monitoring matnini kiriting.', null=True, verbose_name='monitoring matni'),
        ),
        migrations.AddField(
            model_name='monitoring',
            name='m_paragraph_ru',
            field=models.TextField(help_text='Iltimos, monitoring matnini kiriting.', null=True, verbose_name='monitoring matni'),
        ),
        migrations.AddField(
            model_name='monitoring',
            name='m_paragraph_uz',
            field=models.TextField(help_text='Iltimos, monitoring matnini kiriting.', null=True, verbose_name='monitoring matni'),
        ),
        migrations.AddField(
            model_name='news',
            name='n_header_en',
            field=models.CharField(help_text='Iltimos, yangilik sarlavhasini kiriting.', max_length=50, null=True, verbose_name='yangilik sarlavhasi'),
        ),
        migrations.AddField(
            model_name='news',
            name='n_header_ru',
            field=models.CharField(help_text='Iltimos, yangilik sarlavhasini kiriting.', max_length=50, null=True, verbose_name='yangilik sarlavhasi'),
        ),
        migrations.AddField(
            model_name='news',
            name='n_header_uz',
            field=models.CharField(help_text='Iltimos, yangilik sarlavhasini kiriting.', max_length=50, null=True, verbose_name='yangilik sarlavhasi'),
        ),
        migrations.AddField(
            model_name='news',
            name='n_paragraph_en',
            field=ckeditor.fields.RichTextField(help_text='Iltimos, yangilik matnini kiriting.', null=True, verbose_name='yangilik matni'),
        ),
        migrations.AddField(
            model_name='news',
            name='n_paragraph_ru',
            field=ckeditor.fields.RichTextField(help_text='Iltimos, yangilik matnini kiriting.', null=True, verbose_name='yangilik matni'),
        ),
        migrations.AddField(
            model_name='news',
            name='n_paragraph_uz',
            field=ckeditor.fields.RichTextField(help_text='Iltimos, yangilik matnini kiriting.', null=True, verbose_name='yangilik matni'),
        ),
    ]
