# Generated by Django 5.1.7 on 2025-04-16 12:44

import icma.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icma', '0003_article_a_header_en_article_a_header_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(help_text='Iltimos, rasm yuklang (.jpg, .jpeg, .png formatlarida)!', upload_to='photogallery/', validators=[icma.validators.valid_url_extension], verbose_name='Gallereya rasmi')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateField(auto_now=True, verbose_name="O'zgartirilgan vaqti")),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fotolar',
            },
        ),
    ]
