# Generated by Django 5.1.7 on 2025-04-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icma', '0004_photogallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.PositiveIntegerField()),
                ('bot_token', models.CharField(max_length=46)),
            ],
            options={
                'verbose_name': 'TelegramData',
                'verbose_name_plural': 'TelegramDatas',
            },
        ),
    ]
